apiVersion: v1
kind: Template
metadata:
  name: kura-emulator-template
  annotations:
    description: "Eclipse Kura™ emulator instance"
    iconClass: "pficon-virtual-machine"
    tags: "iot"

# Parameters

parameters:
- name:         GIT_BRANCH
  displayName:     Git branch
  value:           master
  required:        true
  description:     The branch from where to pull the files for building the Kura emulator.
                   This is not the branch to pull the Kura sources from.
- name:         KURA_GIT_URI
  displayName:     Kura Git repository
  required:        false
- name:         KURA_GIT_BRANCH
  displayName:     Kura Git Branch
  required:        false
- name:         KURA_COMMIT
  displayName:     Kura commit to build
  required:        false
- name:         VOLUME_SIZE
  value:           2Gi
- name:         VOLUME_STORAGE_CLASS

objects:

# Build configuration

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: centos
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: "7"
      from:
        kind: DockerImage
        name: docker.io/centos:7
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: kura-emulator
    labels:
      app: kura-instance

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: kura-emulator-build
    labels:
      app: kura-instance
  spec:
    triggers: 
      - type: ImageChange
      - type: ConfigChange
    source: 
      type: Git
      git:
        uri: https://github.com/ctron/kura-emulator
        ref: ${GIT_BRANCH}
    strategy: 
      type: Docker
      dockerStrategy:
        env:
          - name: GIT_REPO
            value: ${KURA_GIT_URI}
          - name: GIT_BRANCH
            value: ${KURA_GIT_BRANCH}
          - name: KURA_COMMIT
            value: ${KURA_COMMIT}
    postCommit:
    output: 
      to:
        kind: ImageStreamTag
        name: kura-emulator:latest

# Volume

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: kura-instance-load-config
    labels:
      app: kura-instance

# Service

- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    name: kura-instance
    labels:
      app: kura-instance
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"kura-emulator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"kura-emulator\")].image"}]'
  spec:
    serviceName: kura-instance
    replicas: 1
    selector:
      matchLabels:
        app: kura-instance
        statefulset: kura-instance
    template:
      metadata:
        annotations:
          alpha.image.policy.openshift.io/resolve-names: '*'
        labels:
          app: kura-instance
          statefulset: kura-instance
      spec:
        containers:
        - name: kura-emulator
          image: kura-emulator:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080 
            name: http
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /load
            name: load
        volumes:
        - name: load
          configMap:
            name: kura-instance-load-config

- kind: Service
  apiVersion: v1
  metadata:
    name: kura-instance
    labels:
      app: kura-instance
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: kura-instance
      statefulset: kura-instance

- kind: Route
  apiVersion: v1
  metadata:
    name: console
    labels:
      app: kura-instance
  spec:
    to:
      kind: Service
      name: kura-instance
    port:
      targetPort: http
    tls:
      termination: edge
